pipeline {
  agent {label 'agent1'} 
  tools {
    maven 'mymaven3.5'
  }
  
  stages {
    stage('Check out') { 
      steps {
        git 'https://github.com/jyang49/playground2.git'
      }
    }
    stage('Build') { 
      steps {
        echo 'before dir'
        sh 'mvn -f calculator/pom.xml clean compile'

        /* --------------
           another way of invoking maven
        dir('calculator') {
          echo 'after dir'
          sh 'mvn clean compile'
        }
          --------------- */
      }
    }
    stage('Test') {
      steps {
        sh 'mvn -f calculator/pom.xml test'
      }
    }
  }
}
